# Generated by Django 5.2.3 on 2025-08-13 05:17

import CustomFrame_app.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cap/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('Collection', 'Collection'), ('Delivery', 'Delivery')], max_length=20)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='frames/')),
                ('corner_image', models.ImageField(upload_to='frames/corner/')),
                ('inner_width', models.FloatField()),
                ('inner_height', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MackBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mack_board_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mug_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mug/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pen/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tile/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirt_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tshirt/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tshirt_name'],
            },
        ),
        migrations.CreateModel(
            name='FinishingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='frame_variants/finishes/')),
                ('corner_image', models.ImageField(upload_to='frame_variants/finishes/corner/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_variants', to='CustomFrame_app.frame')),
            ],
            options={
                'unique_together': {('frame', 'finish_name')},
            },
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='frame_variants/colors/')),
                ('corner_image', models.ImageField(upload_to='frame_variants/colors/corner/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='CustomFrame_app.frame')),
            ],
            options={
                'unique_together': {('frame', 'color_name')},
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frames', to='CustomFrame_app.framecategories'),
        ),
        migrations.CreateModel(
            name='FrameHangVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanging_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='hangings_variants/hangings/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameHanging_variant', to='CustomFrame_app.frame')),
            ],
            options={
                'unique_together': {('frame', 'hanging_name')},
            },
        ),
        migrations.CreateModel(
            name='MackBoardColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mack_board_color_images/')),
                ('mack_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='CustomFrame_app.mackboard')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_prints/%Y/%m/%d/')),
                ('quantity', models.PositiveIntegerField()),
                ('lamination', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='CustomFrame_app.documentprintorder')),
                ('lamination_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.laminationtype')),
                ('paper_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.papertype')),
                ('print_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.printsize')),
                ('print_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.printtype')),
            ],
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_width', models.FloatField(blank=True, null=True)),
                ('custom_height', models.FloatField(blank=True, null=True)),
                ('transform_x', models.FloatField(default=0)),
                ('transform_y', models.FloatField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('rotation', models.FloatField(default=0)),
                ('frame_rotation', models.FloatField(default=0)),
                ('adjusted_image', models.ImageField(blank=True, null=True, upload_to='adjusted_images/')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=CustomFrame_app.models.UploadToShortName('original_images/'))),
                ('cropped_image', models.ImageField(blank=True, null=True, upload_to=CustomFrame_app.models.UploadToShortName('cropped_images/'))),
                ('print_width', models.FloatField(blank=True, null=True)),
                ('print_height', models.FloatField(blank=True, null=True)),
                ('print_unit', models.CharField(choices=[('inches', 'Inches'), ('cm', 'Cm')], default='inches', max_length=10)),
                ('media_type', models.CharField(default='Photopaper', max_length=50)),
                ('paper_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fit', models.CharField(choices=[('borderless', 'Borderless'), ('bordered', 'Bordered')], default='borderless', max_length=20)),
                ('border_depth', models.IntegerField(blank=True, default=0, null=True)),
                ('border_color', models.CharField(default='#ffffff', max_length=7)),
                ('border_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('frame_depth', models.IntegerField(blank=True, default=0, null=True)),
                ('custom_frame_color', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.colorvariant')),
                ('finish_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.finishingvariant')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.frame')),
                ('hanging_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.framehangvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SavedItemMackBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=20)),
                ('position', models.IntegerField(default=0)),
                ('mack_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.mackboard')),
                ('mack_board_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.mackboardcolorvariant')),
                ('saved_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mack_boards', to='CustomFrame_app.saveditem')),
            ],
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('inner_width', models.FloatField()),
                ('inner_height', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='frame_variants/sizes/')),
                ('corner_image', models.ImageField(blank=True, null=True, upload_to='frame_variants/sizes/corner/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='CustomFrame_app.frame')),
            ],
            options={
                'unique_together': {('frame', 'size_name')},
            },
        ),
        migrations.AddField(
            model_name='saveditem',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.sizevariant'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_images/')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.colorvariant')),
                ('finish_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.finishingvariant')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.frame')),
                ('hanging_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.framehangvariant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CustomFrame_app.order')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.sizevariant')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='cart/original/')),
                ('cropped_image', models.ImageField(blank=True, null=True, upload_to='cart/cropped/')),
                ('adjusted_image', models.ImageField(blank=True, null=True, upload_to='cart/adjusted/')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('transform_x', models.FloatField(default=0)),
                ('transform_y', models.FloatField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('rotation', models.FloatField(default=0)),
                ('frame_rotation', models.FloatField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CustomFrame_app.cart')),
                ('color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.colorvariant')),
                ('finish_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.finishingvariant')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.frame')),
                ('hanging_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.framehangvariant')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.sizevariant')),
            ],
        ),
        migrations.CreateModel(
            name='TshirtSizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tshirt_variants/sizes/%Y/%m/%d/')),
                ('inner_width', models.FloatField()),
                ('inner_height', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='CustomFrame_app.tshirt')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_user', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='tshirt',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frame',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentprintorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_print_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TshirtColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tshirt_variants/colors/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='CustomFrame_app.tshirt')),
            ],
            options={
                'unique_together': {('tshirt', 'color_name')},
            },
        ),
    ]
