# Generated by Django 5.2.3 on 2025-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='border_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
