# Generated by Django 5.2.3 on 2025-07-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_width', models.FloatField(blank=True, null=True)),
                ('custom_height', models.FloatField(blank=True, null=True)),
                ('transform_x', models.FloatField(default=0)),
                ('transform_y', models.FloatField(default=0)),
                ('scale', models.FloatField(default=1)),
                ('rotation', models.FloatField(default=0)),
                ('frame_rotation', models.FloatField(default=0)),
                ('adjusted_image', models.ImageField(blank=True, null=True, upload_to='adjusted_images/')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='original_images/')),
                ('cropped_image', models.ImageField(blank=True, null=True, upload_to='cropped_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.colorvariant')),
                ('finish_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.finishingvariant')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.frame')),
                ('hanging_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.framehangvariant')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.sizevariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
