# Generated by Django 5.2.3 on 2025-08-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_image', models.ImageField(upload_to='orders/uploaded/%Y/%m/%d/')),
                ('preview_image', models.ImageField(upload_to='orders/preview/%Y/%m/%d/')),
                ('image_position_x', models.FloatField()),
                ('image_position_y', models.FloatField()),
                ('image_scale_x', models.FloatField()),
                ('image_scale_y', models.FloatField()),
                ('image_rotation', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomFrame_app.cap')),
                ('mug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomFrame_app.mug')),
                ('pen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomFrame_app.pens')),
                ('tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomFrame_app.tile')),
                ('tshirt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomFrame_app.tshirt')),
                ('tshirt_color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomFrame_app.tshirtcolorvariant')),
                ('tshirt_size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='CustomFrame_app.tshirtsizevariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
