# Generated by Django 5.2.3 on 2025-06-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0002_cart_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='adjusted_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart/adjusted/'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart/original/'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.colorvariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='finish_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.finishingvariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='hanging_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.framehangvariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.sizevariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
