# Generated by Django 5.2.3 on 2025-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0002_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='border_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='border_depth',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='fit',
            field=models.CharField(choices=[('borderless', 'Borderless'), ('bordered', 'Bordered')], default='borderless', max_length=20),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='media_type',
            field=models.CharField(default='Photopaper', max_length=50),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='paper_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='print_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='print_unit',
            field=models.CharField(choices=[('inches', 'Inches'), ('cm', 'Cm')], default='inches', max_length=10),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='print_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
