# Generated by Django 5.2.3 on 2025-08-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0002_giftorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirtsizevariant',
            name='inner_height',
        ),
        migrations.RemoveField(
            model_name='tshirtsizevariant',
            name='inner_width',
        ),
    ]
