# Generated by Django 5.2.3 on 2025-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0002_saveditem_border_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='custom_frame_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
