# Generated by Django 5.2.3 on 2025-07-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0003_saveditem_custom_frame_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditemmackboard',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
