# Generated by Django 5.2.3 on 2025-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0003_remove_tshirtsizevariant_inner_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtsizevariant',
            name='inner_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tshirtsizevariant',
            name='inner_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
