# Generated by Django 5.2.3 on 2025-06-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0003_remove_cartitem_image_cartitem_adjusted_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart/cropped/'),
        ),
    ]
