# Generated by Django 5.2.3 on 2025-07-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0003_saveditem_border_color_saveditem_border_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
