# Generated by Django 5.2.3 on 2025-08-13 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0004_tshirtsizevariant_inner_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamination', models.BooleanField(default=False)),
                ('delivery_option', models.CharField(choices=[('collection', 'Collection'), ('delivery', 'Delivery')], max_length=20)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_pin', models.CharField(blank=True, max_length=20)),
                ('address_house_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lamination_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.laminationtype')),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.papertype')),
                ('print_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.printsize')),
                ('print_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomFrame_app.printtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='CustomFrame_app.order')),
            ],
        ),
    ]
