# Generated by Django 5.2.3 on 2025-07-29 08:30

import CustomFrame_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0004_saveditemmackboard_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditem',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to=CustomFrame_app.models.UploadToShortName('cropped_images/')),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to=CustomFrame_app.models.UploadToShortName('original_images/')),
        ),
    ]
