# Generated by Django 5.2.3 on 2025-07-08 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0004_saveditem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frames', to='CustomFrame_app.framecategories'),
        ),
    ]
