# Generated by Django 5.2.3 on 2025-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0005_framecategories_frame_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='frame_depth',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
