# Generated by Django 5.2.3 on 2025-08-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0005_docorder_orderfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfile',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='CustomFrame_app.docorder'),
        ),
    ]
