# Generated by Django 5.2.3 on 2025-07-31 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0006_cap_mug_pens_tile_tshirt'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='order_images/')),
                ('image_position_x', models.FloatField(default=0)),
                ('image_position_y', models.FloatField(default=0)),
                ('image_scale_x', models.FloatField(default=1)),
                ('image_scale_y', models.FloatField(default=1)),
                ('image_rotation', models.FloatField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['mug', 'tshirt', 'cap', 'tile', 'pens']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
