# Generated by Django 5.2.3 on 2025-08-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0006_alter_orderfile_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='docorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
