# Generated by Django 5.2.3 on 2025-07-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0006_saveditem_frame_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
