# Generated by Django 5.2.3 on 2025-07-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0007_giftorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
