# Generated by Django 5.2.3 on 2025-07-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0007_saveditem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MackBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mack_board_images/')),
            ],
        ),
    ]
