# Generated by Django 5.2.3 on 2025-08-01 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0008_giftorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MackBoardColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=7)),
                ('mack_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='CustomFrame_app.mackboard')),
            ],
        ),
    ]
