# Generated by Django 5.2.3 on 2025-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0008_giftorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mug',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to='mug/glb/'),
        ),
    ]
