# Generated by Django 5.2.3 on 2025-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0009_mackboardcolorvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mackboardcolorvariant',
            name='color_code',
        ),
        migrations.AddField(
            model_name='mackboardcolorvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mack_board_color_images/'),
        ),
    ]
