# Generated by Django 5.2.3 on 2025-08-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0010_remove_mackboardcolorvariant_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveditem',
            name='mack_boards',
        ),
        migrations.AddField(
            model_name='saveditem',
            name='mack_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.mackboard'),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='mack_board_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.mackboardcolorvariant'),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='mack_board_width',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.DeleteModel(
            name='SavedItemMackBoard',
        ),
    ]
