# Generated by Django 5.2.3 on 2025-08-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0011_remove_saveditem_mack_boards_saveditem_mack_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveditem',
            name='mack_board',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='mack_board_color',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='mack_board_width',
        ),
        migrations.CreateModel(
            name='SavedItemMackBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=20)),
                ('position', models.IntegerField(default=0)),
                ('mack_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.mackboard')),
                ('mack_board_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.mackboardcolorvariant')),
                ('saved_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mack_boards', to='CustomFrame_app.saveditem')),
            ],
        ),
    ]
