# Generated by Django 5.2.3 on 2025-08-02 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0012_remove_saveditem_mack_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrintSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_prints/%Y/%m/%d/')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_method', models.CharField(choices=[('Collection', 'Collection'), ('Delivery', 'Delivery')], max_length=20)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lamination', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_print_orders', to=settings.AUTH_USER_MODEL)),
                ('lamination_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.laminationtype')),
                ('paper_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.papertype')),
                ('print_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.printsize')),
                ('print_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomFrame_app.printtype')),
            ],
        ),
    ]
