# Generated by Django 5.2.3 on 2025-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0013_laminationtype_papertype_printsize_printtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprintorder',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
