# Generated by Django 5.2.3 on 2025-10-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0014_page_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='preview_image',
        ),
    ]
