# Generated by Django 5.2.3 on 2025-08-05 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0014_documentprintorder_address'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftorder',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='preview_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='giftorder',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='giftorder',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['mug', 'tshirt', 'cap', 'tile', 'pen']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='giftorder',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/%Y/%m/%d/'),
        ),
    ]
