# Generated by Django 5.2.3 on 2025-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0015_remove_page_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_previews/'),
        ),
    ]
