# Generated by Django 5.2.3 on 2025-10-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFrame_app', '0016_page_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='photobook_previews/%Y/%m/%d/'),
        ),
    ]
